before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary

checksum:
  disable: true


brews:
  - name: get
    ids: []

    repository:
      owner: "AIO-Develope"
      name: "get"
      
    install: |
      bin.install "get"

    test: |
      system "#{bin}/get --version"
    homepage: "https://aio-web.xyz"

    description: "A simple CLI tool to enhance productivity in git."

    license: "MIT"

    skip_upload: false

    url_template: "https://github.com/AIO-Develope/get/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
