before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary

checksum:
  disable: true


brews:
  - name: your-cli
    description: "Quickly open GitHub repositories"
    homepage: "https://github.com/AIO-Develope/get"
    commit_author:
      name: "GoReleaser Bot"
      email: "bot@goreleaser.com"
    github:
      owner: AIO-Develope
      name: get
    folder: Formula
    caveats: |
      To use this tool, ensure you have the required permissions.
    dependencies:
      - git
    install: |
      bin.install "get"
    test: |
      system "#{bin}/get --version"