before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary

checksum:
  disable: true

brews:
  -
    folder: Formula
    repository:
      owner: AIO-Develope
      name: get
      branch: master

    homepage: https://github.com/AIO-Develope/get
    description: A simple description of your application.